FROM tiangolo/uvicorn-gunicorn-fastapi:python3.8

ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE 1
RUN mkdir -p /home/app
ENV APP_HOME=/home/app/web
RUN mkdir $APP_HOME

WORKDIR $APP_HOME

COPY . $APP_HOME

RUN python3 -m pip install -r $APP_HOME/requirements.txt
EXPOSE 80

CMD [ "gunicorn", "main:app", "--workers" , "6", "--worker-class", "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:80" ]
# CMD [ "gunicorn", "main:app", "--workers" , "6", "--user=root", "--worker-class", "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:80" ]
# CMD ["DEBUG=0", "gunicorn", "main:api", "-w", "4", "-k", "uvicorn.workers.UvicornWorker"]
# CMD ["gunicorn", "-b" , "0.0.0.0:80", "main:api", "-w", "8", "-k", "uvicorn.workers.UvicornWorker"]
# gunicorn --user=nii --workers=4 msmes.wsgi --daemon
# CMD [ "uvicorn", "main:app", "--workers" ,"4","--host", "0.0.0.0", "--port", "80"]
